site_name: EasyPeasyMethod - Thoát khỏi Porn  
site_description: The EasyPeasy way to quit Porn, bản dịch Tiếng Việt
site_author: duykhanh471  

nav:
  - 'Trang chính': index.md
  - 'Chương 0': 'ch00.md'
  - 'Chương 1': 'ch01.md'
  - 'Chương 2': 'ch02.md'
  - 'Chương 3': 'ch03.md'
  - 'Chương 4': 'ch04.md'
  - 'Chương 5': 'ch05.md'
  - 'Chương 6': 'ch06.md'
  - 'Chương 7': 'ch07.md'
  - 'Chương 8': 'ch08.md'
  - 'Chương 9': 'ch09.md'
  - 'Chương 10': 'ch10.md'
  - 'Chương 11': 'ch11.md'
  - 'Chương 12': 'ch12.md'
  - 'Chương 13': 'ch13.md'
  - 'Chương 14': 'ch14.md'
  - 'Chương 15': 'ch15.md'
  - 'Chương 16': 'ch16.md'
  - 'Chương 17': 'ch17.md'
  - 'Chương 18': 'ch18.md'
  - 'Chương 19': 'ch19.md'
  - 'Chương 20': 'ch20.md'
  - 'Chương 21': 'ch21.md'
  - 'Chương 22': 'ch22.md'
  - 'Chương 23': 'ch23.md'
  - 'Chương 24': 'ch24.md'
  - 'Chương 25': 'ch25.md'
  - 'Chương 26': 'ch26.md'
  - 'Chương 27': 'ch27.md'
  - 'Chương 28': 'ch28.md'
  - 'Chương 29': 'ch29.md'
  - 'Chương 30': 'ch30.md'
  - 'Chương 31': 'ch31.md'
  - 'Chương 32': 'ch32.md'



theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlighting
    - search.share
  name: material
  
plugins:
  - search
  # - open-in-new-tab

extra:
  generator: false